language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i -g npm@^3
- npm i -g @angular/cli@latest
script:
- ng lint
- ng test -sr
- .travis/run_build.sh
after_success:
- mkdir packages
- cd dist
- tar czf ../packages/briefyhq-rolleiflex.tar.gz *
- cd ../
- ls -la packages/
- git fetch --unshallow
notifications:
  slack: briefy:qxjOPwcrGEtVx3aCQBr812t9
deploy:
  - provider: s3
    access_key_id: AKIAJB5RBIXPYQ5EU2IA
    secret_access_key:
      secure: Vr7G3KmVxQsng5WuspabeHFoaSo7QJnnLzmGZlBaYcZDGeQI/aD5s1Ui1Vja1UgopJyZdYRUIq3TQwipw9T9zaDPSe+6N/sSzFPxCEtgqaGVzj/16PRmbXGF20nnCvGD3qF1QkjvlpWEdSYgaHZDH1PWZcukAIfbVhIXcQngPCcUsd3fPkh+Bk5tRQScjlioPIF6NnBPXPmaJyLFo+1CKQaxBww/vKEZ9/AgdScMkcVrKKMe4RblvMIcvlBjsAEFQVJYmM6DG1hZi85DvaHUcOA+SGY8cRqznekLuAxM5n9frNDdshEzXNWg9N+2ou9ldL1jqaXks5cmfn2B4eZTjAeg+UNDim8Rlo4sfFewSIo/C9c2M2zkz2T+8gXg6ibuCiXbejEvrDAabkxLVLM6ruqPh5TWBfng3SSnWPNFfnlYA2uO7FXK9A2iJiiF68Dts9gMAcdYozy7S/NNyLfqJwxfYFoVn6tw0Pnx5L5zKqaTBxcRuiiXvLw+maIV4hg3j5bj99TCLjMKLlO7ndw3ryyGaNKTXNrIiFbJ3OWIQFHmzwUsBMi//eQrWWv5GSSg377pAMdoClH/PQE7TktFadOr3RI5DysS0mQ+qUz9zKFnOvVWbmTKzNt1VL1982NDcSnnbpi6zQPul/G76ODVAJfsfHwUKePNcWJrIoxoq6g=
    bucket: app-stg-briefy
    region: us-east-1
    skip_cleanup: true
    local-dir: packages
    upload-dir: packages/${TRAVIS_COMMIT}
    acl: public_read
    on:
      repo: BriefyHQ/briefyhq-rolleiflex
      branch: develop
  - provider: s3
    access_key_id: AKIAJB5RBIXPYQ5EU2IA
    secret_access_key:
      secure: Vr7G3KmVxQsng5WuspabeHFoaSo7QJnnLzmGZlBaYcZDGeQI/aD5s1Ui1Vja1UgopJyZdYRUIq3TQwipw9T9zaDPSe+6N/sSzFPxCEtgqaGVzj/16PRmbXGF20nnCvGD3qF1QkjvlpWEdSYgaHZDH1PWZcukAIfbVhIXcQngPCcUsd3fPkh+Bk5tRQScjlioPIF6NnBPXPmaJyLFo+1CKQaxBww/vKEZ9/AgdScMkcVrKKMe4RblvMIcvlBjsAEFQVJYmM6DG1hZi85DvaHUcOA+SGY8cRqznekLuAxM5n9frNDdshEzXNWg9N+2ou9ldL1jqaXks5cmfn2B4eZTjAeg+UNDim8Rlo4sfFewSIo/C9c2M2zkz2T+8gXg6ibuCiXbejEvrDAabkxLVLM6ruqPh5TWBfng3SSnWPNFfnlYA2uO7FXK9A2iJiiF68Dts9gMAcdYozy7S/NNyLfqJwxfYFoVn6tw0Pnx5L5zKqaTBxcRuiiXvLw+maIV4hg3j5bj99TCLjMKLlO7ndw3ryyGaNKTXNrIiFbJ3OWIQFHmzwUsBMi//eQrWWv5GSSg377pAMdoClH/PQE7TktFadOr3RI5DysS0mQ+qUz9zKFnOvVWbmTKzNt1VL1982NDcSnnbpi6zQPul/G76ODVAJfsfHwUKePNcWJrIoxoq6g=
    bucket: app-stg-briefy
    region: us-east-1
    skip_cleanup: true
    local-dir: packages
    upload-dir: packages/_latest
    acl: public_read
    on:
      repo: BriefyHQ/briefyhq-rolleiflex
      branch: develop
  - provider: s3
    access_key_id: AKIAJB5RBIXPYQ5EU2IA
    secret_access_key:
      secure: Vr7G3KmVxQsng5WuspabeHFoaSo7QJnnLzmGZlBaYcZDGeQI/aD5s1Ui1Vja1UgopJyZdYRUIq3TQwipw9T9zaDPSe+6N/sSzFPxCEtgqaGVzj/16PRmbXGF20nnCvGD3qF1QkjvlpWEdSYgaHZDH1PWZcukAIfbVhIXcQngPCcUsd3fPkh+Bk5tRQScjlioPIF6NnBPXPmaJyLFo+1CKQaxBww/vKEZ9/AgdScMkcVrKKMe4RblvMIcvlBjsAEFQVJYmM6DG1hZi85DvaHUcOA+SGY8cRqznekLuAxM5n9frNDdshEzXNWg9N+2ou9ldL1jqaXks5cmfn2B4eZTjAeg+UNDim8Rlo4sfFewSIo/C9c2M2zkz2T+8gXg6ibuCiXbejEvrDAabkxLVLM6ruqPh5TWBfng3SSnWPNFfnlYA2uO7FXK9A2iJiiF68Dts9gMAcdYozy7S/NNyLfqJwxfYFoVn6tw0Pnx5L5zKqaTBxcRuiiXvLw+maIV4hg3j5bj99TCLjMKLlO7ndw3ryyGaNKTXNrIiFbJ3OWIQFHmzwUsBMi//eQrWWv5GSSg377pAMdoClH/PQE7TktFadOr3RI5DysS0mQ+qUz9zKFnOvVWbmTKzNt1VL1982NDcSnnbpi6zQPul/G76ODVAJfsfHwUKePNcWJrIoxoq6g=
    bucket: app-live-briefy
    region: eu-central-1
    skip_cleanup: true
    local-dir: packages
    upload-dir: packages/_latest
    acl: public_read
    on:
      repo: BriefyHQ/briefyhq-rolleiflex
      branch: master
  - provider: deis
    controller: https://deis.stg.briefy.co
    cli_version: v2.4.0
    app: briefyhq-rolleiflex
    username: ci
    password:
      secure: Pha+9iskXdTdFu8uMeVqRhDX8lGrKqhJm2k99kiyM8bQU4WmmK7CTLdKsVuMA8DWkqS9d9MFMZc8G31/n6/nj10DxuvlHQtatro9HNO21Y1GWq+gsMDYWoV0FIAkHYdujdM8fFr81xJ1s2jbf0eOJkpuIML7uihNpQXxzYTT3e1CJRlZdL1i/zsJcl6dfugdndOZBjQFRHV6BW6lbepVBiHbc/hcUIm+JeG5EE+1gYp77DA9j2kn0t+I/FnpqQtPBmtpfwmYIKnRIts3CChMdvKicqlugIwa5KUnR+/WPcp92JNaErQwnFZw5nCE6tw5MoD9Y2ZTD2ZLgGQ2U9S3VVJu5GZGhOsa83nYhCusBCRaBnOHfAfGS1NM+7MGZ2UnjlvJn9qLBtSy8IYaiWJsxAfcn3ZgcOndDfIzsJc3LYM4es+1IQXMJse7kG6b8fYuZu6xJyyoFKzvBpNmjJ+ypgr7TIpweMh6CjK6e9J0WnbW39CWdIopauSeLIf2UI52vVMNRfwSj21ycb8m5sqrnwqWOcGbamf/EPgFBvpwNgollfW0S2hK3Ws3sX9RImCm3YBKEE3xwzTNNdNOnb2XBkaM2qAeO5jbXtZFLmEUBYzCf7KRVY64uxH/OfzaCmEGGToO6e99TBo9HezcPeOb84i6caBbCqqN0FV1ta6VUg8=
    on:
      repo: BriefyHQ/briefyhq-rolleiflex
      branch: develop
